name: ferry_graphql_v1
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ferry: ^0.10.4
  get_it: ^7.2.0
  ferry_flutter: ^0.5.4
  gql_http_link: ^0.4.0
  analyzer: ^1.7.2
  curved_navigation_bar: ^1.0.3
  flutter_slidable: ^1.2.0
  loadmore: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  ferry_generator: ^0.4.4
  build_runner: ^2.1.7

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
